"""v5: DERIVED gapped-sequence display of each accepted pair, generated by SQARMA from (a) the selected original
STAR3D output mapped through the residue crosswalk and (b) the ordinary Rfam seed correspondence.
This is a SQARMA visualisation, NOT STAR3D's raw output (raw: the .aln listed in results/primary_star3d_outputs.tsv).
Every reported residue correspondence is shown exactly once; unmatched residues are placed opposite gaps in sequence
order; no correspondence is invented. A self-check re-derives the pairs from the gapped strings.
Output: results/derived_alignment_views.md and results/derived_alignment_views.tsv"""
import csv
import os
from collections import defaultdict

ROOT = os.environ.get("SQARMA_STUDY_ROOT") or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
R = lambda p: list(csv.DictReader(open(P(p)), delimiter="\t"))  # noqa: E731


def gapped(seq_a, seq_b, pairs):
    """pairs: sorted list of (i, j), 1-based, strictly increasing in both. Returns aligned strings."""
    a, b, i0, j0 = [], [], 1, 1
    for i, j in pairs + [(len(seq_a) + 1, len(seq_b) + 1)]:
        while i0 < i:
            a.append(seq_a[i0 - 1]); b.append("-"); i0 += 1
        while j0 < j:
            a.append("-"); b.append(seq_b[j0 - 1]); j0 += 1
        if i <= len(seq_a):
            a.append(seq_a[i - 1]); b.append(seq_b[j - 1]); i0, j0 = i + 1, j + 1
    return "".join(a), "".join(b)


def rederive(sa, sb):
    out, i, j = [], 0, 0
    for x, y in zip(sa, sb):
        i += x != "-"
        j += y != "-"
        if x != "-" and y != "-":
            out.append((i, j))
    return out


def main():
    cw = defaultdict(dict)
    for r in R("results/residue_crosswalk.tsv"):
        cw[r["rep_id"]][int(r["row_index1"])] = r
    comp = defaultdict(list)
    for r in R("results/correspondence_comparison.tsv"):
        comp[r["pair_id"]].append(r)
    prim = {r["pair_id"]: r for r in R("results/primary_star3d_outputs.tsv")}
    md = ["# Derived alignment views (generated by SQARMA; NOT STAR3D raw output)", "",
          "Each block shows the same two RNAs aligned two ways, reconstructed from residue correspondences:",
          "**seed** = ordinary Rfam seed 15.1 correspondence; **STAR3D** = the selected original STAR3D v1.2 output "
          "(one forward run) mapped through the residue crosswalk. Residues are row indices (= author numbers for these "
          "chains). `-` = no partner. Lower-case = residue without coordinates. The raw STAR3D file is named under "
          "each block.", ""]
    tsv = []
    for p in R("results/selected_pairs.tsv"):
        pid = p["pair_id"]
        q, t = cw[p["query_rep"]], cw[p["target_rep"]]
        sq = "".join(q[k]["row_nt"] if q[k]["observed"] == "yes" else q[k]["row_nt"].lower() for k in sorted(q))
        st = "".join(t[k]["row_nt"] if t[k]["observed"] == "yes" else t[k]["row_nt"].lower() for k in sorted(t))
        rows = sorted(comp[pid], key=lambda r: int(r["source_row_index"]))
        for meth, col in (("seed", "rfam_partner"), ("STAR3D", "star3d_partner")):
            pairs = sorted((int(r["source_row_index"]), int(r[col])) for r in rows if r[col] != "NA")
            if any(b2 <= b1 for (_, b1), (_, b2) in zip(pairs, pairs[1:])):
                raise SystemExit(f"{pid} {meth}: correspondence not order-preserving; cannot draw as one gapped alignment")
            ga, gb = gapped(sq, st, pairs)
            assert rederive(ga, gb) == pairs, f"{pid} {meth}: self-check failed"
            assert ga.replace("-", "") == sq and gb.replace("-", "") == st
            tsv.append(dict(pair_id=pid, method=meth, query=p["query"], target=p["target"], n_correspondences=len(pairs),
                            query_gapped=ga, target_gapped=gb))
        md += [f"## {pid}", "", "```"]
        for t_ in tsv[-2:]:
            md += [f"{t_['method']:<7} {p['query']:<7} {t_['query_gapped']}", f"{'':<7} {p['target']:<7} {t_['target_gapped']}",
                   f"{'':<7} ({t_['n_correspondences']} correspondences)", ""]
        md += ["```", f"Raw STAR3D output: `{prim[pid]['output_aln']}` (sha256 {prim[pid]['output_sha256'][:16]}…)", ""]
    open(P("results/derived_alignment_views.md"), "w").write("\n".join(md))
    with open(P("results/derived_alignment_views.tsv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(tsv[0]), delimiter="\t", lineterminator="\n")
        w.writeheader()
        w.writerows(tsv)
    print("\n".join(md[8:30]))


if __name__ == "__main__":
    main()
