"""Write reports/evidence_cards.md: one card per selected RNA, generated from recorded tables only."""
import csv
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
R = lambda p: list(csv.DictReader(open(P(p), encoding="utf-8"), delimiter="\t"))  # noqa: E731
reps = R("results/selected_representatives.tsv")
links = {f"{r['pdb_id']}_{r['chain_token']}": r for r in R("mappings/structure_sequence_map.tsv") if r["link_basis"] == "explicit_GR_feature"}
mem = {r["rep_id"]: r for r in R("results/standard_seed_membership.tsv")}
dec = yaml.safe_load(open(P("review/decisions.yaml")))["families"]
ex = {r["key"]: r for r in R("review/exact_source_check.tsv")} if os.path.exists(P("review/exact_source_check.tsv")) else {}
VOCAB = ("Status vocabulary: evidence_strength = exact_source_genome | core_exact_source_genome | literature_supported_only | "
         "related_species_only | conflicting_metadata; engineering_status = confirmed_absent | terminal_only | "
         "present_documented | unknown | not_applicable. 'none' is never used for an unknown.")
out = ["# Evidence cards — selected RNAs (cohort v1)", "",
       "Generated by scripts/evidence_cards.py from recorded tables (cohort v1.1); reviewer AI agent; no human review or approval.",
       "", VOCAB, ""]
for r in reps:
    k = r["key"]
    L = links[k]
    d = next(x for x in dec[r["rfam_acc"]]["representatives"] if x["key"] == k)
    m = mem.get(r["rep_id"], {})
    out += [f"## {r['rep_id']}  (family tier: {r['family_decision']}; representative decision: {d['decision']})", "",
            f"- **Identity:** PDB {L['pdb_id']}, entity {L['entity_id']}, author chain {L['auth_asym_id']} / label chain {L['label_asym_id']}, model 1 of {L['n_models']}; {L['exptl_method']} {L['resolution']} Å; released {L['initial_release_date']}",
            f"- **Title / citation:** {L['title']} — {L['primary_citation']}",
            f"- **Organism / source:** {d.get('source')}",
            f"- **Source evidence:** {d.get('source_evidence')}",
            "- **mmCIF RNA-entity source records:** " + (
                (L['entity_source_records'].replace("None|taxid=None", "organism field empty in mmCIF")
                 if L['entity_source_records'] not in ("", "NA") else "no source category present in mmCIF")) +
            f" (expression-host records: {L['expression_host_records'] if L['expression_host_records'] not in ('', 'NA') else 'none recorded'})",
            f"- **Exact standard-seed row:** `{L['row_name']}` in Rfam.seed.gz 15.1 (decompressed lines {L['seed_row_lines']}; aligned sha256 {L['seed_row_aligned_sha256'][:16]}…; membership {m.get('membership_status', 'NA')}; link basis {L['link_basis']} `{L['gr_feature']}`)",
            f"- **Sequence match:** {L['sequence_match']}; deposited length {L['deposited_len']}; family interval label {L['family_label_seq_start']}-{L['family_label_seq_end']} (author {L['family_auth_start']}-{L['family_auth_end']})",
            f"- **Evidence strength (source):** `{d.get('evidence_strength', 'unknown')}`" +
            (f" — exact-source genome check {ex[k]['accession']}: full interval {ex[k]['family_interval_exact_hits']}, "
             f"core {ex[k]['core_label_range']} {ex[k]['core_exact_hits']} → {ex[k]['verdict']}" if k in ex else
             " — no exact-source genome check (no reference genome used)"),
            f"- **Engineering status:** `{d.get('engineering_status', 'unknown')}`; construct changes: {d.get('construct_changes')}",
            "- **Masked (engineered) label positions:** " + (
                f"{d.get('masked')}" if d.get("masked") else
                ("none — engineering confirmed absent (exact source match)" if d.get("engineering_status") == "confirmed_absent"
                 else f"none defined ({d.get('engineering_status', 'unknown')})")),
            f"- **Coverage:** observed fraction {L['observed_fraction']} of row; residues without coordinates (label): "
            f"{L['missing_residue_seq_ids'] if L['missing_residue_seq_ids'] not in ('', 'NA') else 'none'}; residues missing "
            f"some STAR3D backbone atoms (label): {L['incomplete_backbone_seq_ids'] if L['incomplete_backbone_seq_ids'] not in ('', 'NA') else 'none'}",
            f"- **Modified nucleotides:** {L['modified_residues'] if L['modified_residues'] not in ('', 'NA') else 'none in the deposited chain (pdbx_poly_seq_scheme checked)'}",
            f"- **Ligands / context:** {L['ligands']}; other polymer entities: {L['n_other_polymer_entities']}; ligand state: {d.get('ligand_state')}",
            f"- **Selection reason / alternatives:** {d.get('alternatives', 'only candidate for this source')}; rule order in config.yaml representative_rule", ""]
open(P("reports/evidence_cards.md"), "w").write("\n".join(out))
print(len(reps), "cards")
