"""Write reports/evidence_cards.md: one card per selected RNA, generated from recorded tables only."""
import csv
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = lambda *a: os.path.join(ROOT, *a)  # noqa: E731
R = lambda p: list(csv.DictReader(open(P(p), encoding="utf-8"), delimiter="\t"))  # noqa: E731
reps = R("results/selected_representatives.tsv")
links = {f"{r['pdb_id']}_{r['chain_token']}": r for r in R("mappings/structure_sequence_map.tsv") if r["link_basis"] == "explicit_GR_feature"}
mem = {r["rep_id"]: r for r in R("results/standard_seed_membership.tsv")}
dec = yaml.safe_load(open(P("review/decisions.yaml")))["families"]
out = ["# Evidence cards — selected RNAs (cohort v1)", "",
       "Generated by scripts/evidence_cards.py from recorded tables; reviewer AI agent; no human approval claimed.", ""]
for r in reps:
    k = r["key"]
    L = links[k]
    d = next(x for x in dec[r["rfam_acc"]]["representatives"] if x["key"] == k)
    m = mem.get(r["rep_id"], {})
    out += [f"## {r['rep_id']}  ({r['family_decision']} family; decision: {d['decision']})", "",
            f"- **Identity:** PDB {L['pdb_id']}, entity {L['entity_id']}, author chain {L['auth_asym_id']} / label chain {L['label_asym_id']}, model 1 of {L['n_models']}; {L['exptl_method']} {L['resolution']} Å; released {L['initial_release_date']}",
            f"- **Title / citation:** {L['title']} — {L['primary_citation']}",
            f"- **Organism / source:** {d.get('source')}",
            f"- **Source evidence:** {d.get('source_evidence')}",
            f"- **mmCIF RNA-entity source records:** {L['entity_source_records']} (host records: {L['expression_host_records']})",
            f"- **Exact standard-seed row:** `{L['row_name']}` in Rfam.seed.gz 15.1 (decompressed lines {L['seed_row_lines']}; aligned sha256 {L['seed_row_aligned_sha256'][:16]}…; membership {m.get('membership_status', 'NA')}; link basis {L['link_basis']} `{L['gr_feature']}`)",
            f"- **Sequence match:** {L['sequence_match']}; deposited length {L['deposited_len']}; family interval label {L['family_label_seq_start']}-{L['family_label_seq_end']} (author {L['family_auth_start']}-{L['family_auth_end']}); modifications: {L['modified_residues']}",
            f"- **Construct changes:** {d.get('construct_changes')}",
            f"- **Masked (engineered) label positions:** {d.get('masked') or 'none'}",
            f"- **Coverage:** observed fraction {L['observed_fraction']} of row; missing residues (label): {L['missing_residue_seq_ids']}; incomplete STAR3D backbone atoms: {L['incomplete_backbone_seq_ids']}",
            f"- **Ligands / context:** {L['ligands']}; other polymer entities: {L['n_other_polymer_entities']}; ligand state: {d.get('ligand_state')}",
            f"- **Selection reason / alternatives:** {d.get('alternatives', 'only candidate for this source')}; rule order in config.yaml representative_rule", ""]
open(P("reports/evidence_cards.md"), "w").write("\n".join(out))
print(len(reps), "cards")
